# Generated by Django 4.2.3 on 2023-07-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_categoria_valor_planejamento_alter_conta_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='valor_planejamento',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='conta',
            name='valor',
            field=models.FloatField(),
        ),
    ]
