# Generated by Django 4.2.3 on 2023-07-07 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapaga',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.contapagar'),
        ),
    ]
