name: CI

on: 
  push: 
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
        
      - uses: actions/checkout@v4.1.2

      - name: Docker Login           
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
            context: .
            file: .
            push: true
            tags: |
              warleihc21/finan.ce:v1
              warleihc21/finan.ce:latest